spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: akahuc
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION}